# √Ä modifier avec le nom et la description du site
site_name: "Maths algorithmique - BTS SIO SISR 1√®re ann√©e"
site_description: "Cours de math√©matiques pour l'informatique du BTS SIO"

# Auteur / d√©p√¥t / URL (version GitHub Pages)
site_url: "https://yahnlp.github.io/bts1-sio-sisr-math_algo/"
site_author: "Yahn Le Prettre"
repo_url: "https://github.com/YahnLP/bts1-sio-math_algo"
edit_uri: "edit/main/docs/"

# √Ä modifier, avec votre nom et la licence choisie
copyright: |
  <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr">
    <img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" />
  </a>
  <br/>
  H√©berg√© sur GitHub Pages

# √Ä modifier, avec votre mail
extra:
  social:
    - icon: fontawesome/regular/envelope
      link: "mailto:yahn.leprettre.mfr@gmail.com"
      name: "√âcrire √† l'auteur"
    - icon: fontawesome/brands/github
      link: "https://github.com/YahnLP/bts1-sio-sisr-math_algo"
      name: "GitHub"

docs_dir: docs

# √âventuellement √† modifier avec votre th√®me de couleurs
theme:
  name: material
  language: fr
  font: false # RGPD ; pas de fonte Google

  # ‚ö†Ô∏è Si ces fichiers n'existent pas dans docs/images/, commente ces 2 lignes
  favicon: images/favicon.png
  logo: images/logo-b1.png

  # ‚ö†Ô∏è Si ce dossier n'existe pas √† la racine, commente cette ligne
  custom_dir: my_theme_customizations/

  palette: # Palettes de couleurs jour/nuit
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: "Passer au mode nuit"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-night
        name: "Passer au mode jour"

  features:
    - navigation.instant
    # - navigation.tabs   Pour avoir le menu vertical il fallait supprimer √ßa
    - navigation.top
    - toc.integrate
    - header.autohide
    - content.code.annotate

nav:
  - "üè° Accueil": index.md
  - ... | regex=^(?:(?!_REM.md).)*$

markdown_extensions:
  - meta
  - abbr
  - def_list
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      auto_title: true
      auto_title_map:
        Python: "üêç Script Python"
        Python Console Session: "üêç Console Python"
        Text Only: "üìã Texte"
        E-mail: "üì• Entr√©e"
        Text Output: "üì§ Sortie"
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "‚öìÔ∏é"
      toc_depth: 2

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
  - macros
  # - tags:
  #     tags_file: defis.md

extra_javascript:
  - xtra/javascripts/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - xtra/stylesheets/qcm.css
  - xtra/stylesheets/ajustements.css
